/**
 * kommunlan.ts — Sveriges 290 kommuner: slug, namn, län. Facit-tabell,
 * genererad EN GÅNG från SCB:s officiella Region-variabel
 * (api.scb.se/OV0104/v1/doris/sv/ssd/START/BE/BE0101/BE0101A/FolkmangdNov,
 * 2026-07-27) — inte Wikipedias "X kommun"-fraser, som är i genitivform
 * och inte reversibla till bas-namn (t.ex. "Arjeplogs kommun" → basnamnet
 * är "Arjeplog", inte "Arjeplogs"; ett naivt suffix-strip hade gett fel
 * resultat för namn som redan slutar på "s", t.ex. Kramfors/Mönsterås).
 *
 * Validerar BÅDA sakerna Jacob beställde 2026-07-27 i samma tabell:
 * (1) loadKommuner() ska avvisa en okänd kommun_slug (norrkoeping,
 * vestervik, harryrda, falkopping-klassen av fel) som ETT FEL, inte en
 * varning — det finns inga andra kommuner än de 290 här.
 * (2) loadKommuner() ska avvisa en kommun-YAML vars `lan`-fält inte
 * matchar denna tabells län för den kommunen.
 *
 * KÄND AVVIKELSE (flaggad, inte tyst vald): Håbo (kod 0305, Uppsala län)
 * och Habo (kod 0643, Jönköpings län) viker båda till slugen "habo" efter
 * å/ä/ö-normalisering — enda kollisionen bland 290. Håbo har fått
 * "habo-uppsala" här tills Jacob/Fable bestämmer en slutgiltig konvention
 * (ingen av dem finns i data/kommuner/ än, så inget existerande brutet).
 */

export interface KommunFacit {
  kod: string;
  slug: string;
  namn: string;
  lan: string;
}

export const KOMMUNFACIT: readonly KommunFacit[] = [
  { kod: '1440', slug: 'ale', namn: "Ale", lan: "Västra Götalands län" },
  { kod: '1489', slug: 'alingsas', namn: "Alingsås", lan: "Västra Götalands län" },
  { kod: '0765', slug: 'almhult', namn: "Älmhult", lan: "Kronobergs län" },
  { kod: '2039', slug: 'alvdalen', namn: "Älvdalen", lan: "Dalarnas län" },
  { kod: '0764', slug: 'alvesta', namn: "Alvesta", lan: "Kronobergs län" },
  { kod: '0319', slug: 'alvkarleby', namn: "Älvkarleby", lan: "Uppsala län" },
  { kod: '2560', slug: 'alvsbyn', namn: "Älvsbyn", lan: "Norrbottens län" },
  { kod: '1492', slug: 'amal', namn: "Åmål", lan: "Västra Götalands län" },
  { kod: '0604', slug: 'aneby', namn: "Aneby", lan: "Jönköpings län" },
  { kod: '2260', slug: 'ange', namn: "Ånge", lan: "Västernorrlands län" },
  { kod: '1292', slug: 'angelholm', namn: "Ängelholm", lan: "Skåne län" },
  { kod: '1984', slug: 'arboga', namn: "Arboga", lan: "Västmanlands län" },
  { kod: '2321', slug: 'are', namn: "Åre", lan: "Jämtlands län" },
  { kod: '1765', slug: 'arjang', namn: "Årjäng", lan: "Värmlands län" },
  { kod: '2506', slug: 'arjeplog', namn: "Arjeplog", lan: "Norrbottens län" },
  { kod: '2505', slug: 'arvidsjaur', namn: "Arvidsjaur", lan: "Norrbottens län" },
  { kod: '1784', slug: 'arvika', namn: "Arvika", lan: "Värmlands län" },
  { kod: '2463', slug: 'asele', namn: "Åsele", lan: "Västerbottens län" },
  { kod: '1882', slug: 'askersund', namn: "Askersund", lan: "Örebro län" },
  { kod: '1277', slug: 'astorp', namn: "Åstorp", lan: "Skåne län" },
  { kod: '0561', slug: 'atvidaberg', namn: "Åtvidaberg", lan: "Östergötlands län" },
  { kod: '2084', slug: 'avesta', namn: "Avesta", lan: "Dalarnas län" },
  { kod: '1278', slug: 'bastad', namn: "Båstad", lan: "Skåne län" },
  { kod: '1460', slug: 'bengtsfors', namn: "Bengtsfors", lan: "Västra Götalands län" },
  { kod: '2326', slug: 'berg', namn: "Berg", lan: "Jämtlands län" },
  { kod: '2403', slug: 'bjurholm', namn: "Bjurholm", lan: "Västerbottens län" },
  { kod: '1260', slug: 'bjuv', namn: "Bjuv", lan: "Skåne län" },
  { kod: '2582', slug: 'boden', namn: "Boden", lan: "Norrbottens län" },
  { kod: '1443', slug: 'bollebygd', namn: "Bollebygd", lan: "Västra Götalands län" },
  { kod: '2183', slug: 'bollnas', namn: "Bollnäs", lan: "Gävleborgs län" },
  { kod: '1490', slug: 'boras', namn: "Borås", lan: "Västra Götalands län" },
  { kod: '0885', slug: 'borgholm', namn: "Borgholm", lan: "Kalmar län" },
  { kod: '2081', slug: 'borlange', namn: "Borlänge", lan: "Dalarnas län" },
  { kod: '0127', slug: 'botkyrka', namn: "Botkyrka", lan: "Stockholms län" },
  { kod: '0560', slug: 'boxholm', namn: "Boxholm", lan: "Östergötlands län" },
  { kod: '2305', slug: 'bracke', namn: "Bräcke", lan: "Jämtlands län" },
  { kod: '1272', slug: 'bromolla', namn: "Bromölla", lan: "Skåne län" },
  { kod: '1231', slug: 'burlov', namn: "Burlöv", lan: "Skåne län" },
  { kod: '1438', slug: 'dals-ed', namn: "Dals-Ed", lan: "Västra Götalands län" },
  { kod: '0162', slug: 'danderyd', namn: "Danderyd", lan: "Stockholms län" },
  { kod: '1862', slug: 'degerfors', namn: "Degerfors", lan: "Örebro län" },
  { kod: '2425', slug: 'dorotea', namn: "Dorotea", lan: "Västerbottens län" },
  { kod: '1730', slug: 'eda', namn: "Eda", lan: "Värmlands län" },
  { kod: '0125', slug: 'ekero', namn: "Ekerö", lan: "Stockholms län" },
  { kod: '0686', slug: 'eksjo', namn: "Eksjö", lan: "Jönköpings län" },
  { kod: '0862', slug: 'emmaboda', namn: "Emmaboda", lan: "Kalmar län" },
  { kod: '0381', slug: 'enkoping', namn: "Enköping", lan: "Uppsala län" },
  { kod: '0484', slug: 'eskilstuna', namn: "Eskilstuna", lan: "Södermanlands län" },
  { kod: '1285', slug: 'eslov', namn: "Eslöv", lan: "Skåne län" },
  { kod: '1445', slug: 'essunga', namn: "Essunga", lan: "Västra Götalands län" },
  { kod: '1982', slug: 'fagersta', namn: "Fagersta", lan: "Västmanlands län" },
  { kod: '1382', slug: 'falkenberg', namn: "Falkenberg", lan: "Hallands län" },
  { kod: '1499', slug: 'falkoping', namn: "Falköping", lan: "Västra Götalands län" },
  { kod: '2080', slug: 'falun', namn: "Falun", lan: "Dalarnas län" },
  { kod: '1439', slug: 'fargelanda', namn: "Färgelanda", lan: "Västra Götalands län" },
  { kod: '1782', slug: 'filipstad', namn: "Filipstad", lan: "Värmlands län" },
  { kod: '0562', slug: 'finspang', namn: "Finspång", lan: "Östergötlands län" },
  { kod: '0482', slug: 'flen', namn: "Flen", lan: "Södermanlands län" },
  { kod: '1763', slug: 'forshaga', namn: "Forshaga", lan: "Värmlands län" },
  { kod: '2026', slug: 'gagnef', namn: "Gagnef", lan: "Dalarnas län" },
  { kod: '2523', slug: 'gallivare', namn: "Gällivare", lan: "Norrbottens län" },
  { kod: '2180', slug: 'gavle', namn: "Gävle", lan: "Gävleborgs län" },
  { kod: '0662', slug: 'gislaved', namn: "Gislaved", lan: "Jönköpings län" },
  { kod: '0461', slug: 'gnesta', namn: "Gnesta", lan: "Södermanlands län" },
  { kod: '0617', slug: 'gnosjo', namn: "Gnosjö", lan: "Jönköpings län" },
  { kod: '1480', slug: 'goteborg', namn: "Göteborg", lan: "Västra Götalands län" },
  { kod: '1471', slug: 'gotene', namn: "Götene", lan: "Västra Götalands län" },
  { kod: '0980', slug: 'gotland', namn: "Gotland", lan: "Gotlands län" },
  { kod: '1444', slug: 'grastorp', namn: "Grästorp", lan: "Västra Götalands län" },
  { kod: '1764', slug: 'grums', namn: "Grums", lan: "Värmlands län" },
  { kod: '1447', slug: 'gullspang', namn: "Gullspång", lan: "Västra Götalands län" },
  { kod: '0643', slug: 'habo', namn: "Habo", lan: "Jönköpings län" },
  { kod: '0305', slug: 'habo-uppsala', namn: "Håbo", lan: "Uppsala län" },
  { kod: '1783', slug: 'hagfors', namn: "Hagfors", lan: "Värmlands län" },
  { kod: '1863', slug: 'hallefors', namn: "Hällefors", lan: "Örebro län" },
  { kod: '1861', slug: 'hallsberg', namn: "Hallsberg", lan: "Örebro län" },
  { kod: '1961', slug: 'hallstahammar', namn: "Hallstahammar", lan: "Västmanlands län" },
  { kod: '1380', slug: 'halmstad', namn: "Halmstad", lan: "Hallands län" },
  { kod: '1761', slug: 'hammaro', namn: "Hammarö", lan: "Värmlands län" },
  { kod: '0136', slug: 'haninge', namn: "Haninge", lan: "Stockholms län" },
  { kod: '2583', slug: 'haparanda', namn: "Haparanda", lan: "Norrbottens län" },
  { kod: '2361', slug: 'harjedalen', namn: "Härjedalen", lan: "Jämtlands län" },
  { kod: '2280', slug: 'harnosand', namn: "Härnösand", lan: "Västernorrlands län" },
  { kod: '1401', slug: 'harryda', namn: "Härryda", lan: "Västra Götalands län" },
  { kod: '1293', slug: 'hassleholm', namn: "Hässleholm", lan: "Skåne län" },
  { kod: '0331', slug: 'heby', namn: "Heby", lan: "Uppsala län" },
  { kod: '2083', slug: 'hedemora', namn: "Hedemora", lan: "Dalarnas län" },
  { kod: '1283', slug: 'helsingborg', namn: "Helsingborg", lan: "Skåne län" },
  { kod: '1466', slug: 'herrljunga', namn: "Herrljunga", lan: "Västra Götalands län" },
  { kod: '1497', slug: 'hjo', namn: "Hjo", lan: "Västra Götalands län" },
  { kod: '2104', slug: 'hofors', namn: "Hofors", lan: "Gävleborgs län" },
  { kod: '1284', slug: 'hoganas', namn: "Höganäs", lan: "Skåne län" },
  { kod: '0821', slug: 'hogsby', namn: "Högsby", lan: "Kalmar län" },
  { kod: '1267', slug: 'hoor', namn: "Höör", lan: "Skåne län" },
  { kod: '1266', slug: 'horby', namn: "Hörby", lan: "Skåne län" },
  { kod: '0126', slug: 'huddinge', namn: "Huddinge", lan: "Stockholms län" },
  { kod: '2184', slug: 'hudiksvall', namn: "Hudiksvall", lan: "Gävleborgs län" },
  { kod: '0860', slug: 'hultsfred', namn: "Hultsfred", lan: "Kalmar län" },
  { kod: '1315', slug: 'hylte', namn: "Hylte", lan: "Hallands län" },
  { kod: '0123', slug: 'jarfalla', namn: "Järfälla", lan: "Stockholms län" },
  { kod: '2510', slug: 'jokkmokk', namn: "Jokkmokk", lan: "Norrbottens län" },
  { kod: '0680', slug: 'jonkoping', namn: "Jönköping", lan: "Jönköpings län" },
  { kod: '2514', slug: 'kalix', namn: "Kalix", lan: "Norrbottens län" },
  { kod: '0880', slug: 'kalmar', namn: "Kalmar", lan: "Kalmar län" },
  { kod: '1446', slug: 'karlsborg', namn: "Karlsborg", lan: "Västra Götalands län" },
  { kod: '1082', slug: 'karlshamn', namn: "Karlshamn", lan: "Blekinge län" },
  { kod: '1883', slug: 'karlskoga', namn: "Karlskoga", lan: "Örebro län" },
  { kod: '1080', slug: 'karlskrona', namn: "Karlskrona", lan: "Blekinge län" },
  { kod: '1780', slug: 'karlstad', namn: "Karlstad", lan: "Värmlands län" },
  { kod: '0483', slug: 'katrineholm', namn: "Katrineholm", lan: "Södermanlands län" },
  { kod: '1261', slug: 'kavlinge', namn: "Kävlinge", lan: "Skåne län" },
  { kod: '1715', slug: 'kil', namn: "Kil", lan: "Värmlands län" },
  { kod: '0513', slug: 'kinda', namn: "Kinda", lan: "Östergötlands län" },
  { kod: '2584', slug: 'kiruna', namn: "Kiruna", lan: "Norrbottens län" },
  { kod: '1276', slug: 'klippan', namn: "Klippan", lan: "Skåne län" },
  { kod: '0330', slug: 'knivsta', namn: "Knivsta", lan: "Uppsala län" },
  { kod: '1983', slug: 'koping', namn: "Köping", lan: "Västmanlands län" },
  { kod: '2282', slug: 'kramfors', namn: "Kramfors", lan: "Västernorrlands län" },
  { kod: '1290', slug: 'kristianstad', namn: "Kristianstad", lan: "Skåne län" },
  { kod: '1781', slug: 'kristinehamn', namn: "Kristinehamn", lan: "Värmlands län" },
  { kod: '2309', slug: 'krokom', namn: "Krokom", lan: "Jämtlands län" },
  { kod: '1881', slug: 'kumla', namn: "Kumla", lan: "Örebro län" },
  { kod: '1482', slug: 'kungalv', namn: "Kungälv", lan: "Västra Götalands län" },
  { kod: '1384', slug: 'kungsbacka', namn: "Kungsbacka", lan: "Hallands län" },
  { kod: '1960', slug: 'kungsor', namn: "Kungsör", lan: "Västmanlands län" },
  { kod: '1381', slug: 'laholm', namn: "Laholm", lan: "Hallands län" },
  { kod: '1282', slug: 'landskrona', namn: "Landskrona", lan: "Skåne län" },
  { kod: '1860', slug: 'laxa', namn: "Laxå", lan: "Örebro län" },
  { kod: '1814', slug: 'lekeberg', namn: "Lekeberg", lan: "Örebro län" },
  { kod: '2029', slug: 'leksand', namn: "Leksand", lan: "Dalarnas län" },
  { kod: '1441', slug: 'lerum', namn: "Lerum", lan: "Västra Götalands län" },
  { kod: '0761', slug: 'lessebo', namn: "Lessebo", lan: "Kronobergs län" },
  { kod: '0186', slug: 'lidingo', namn: "Lidingö", lan: "Stockholms län" },
  { kod: '1494', slug: 'lidkoping', namn: "Lidköping", lan: "Västra Götalands län" },
  { kod: '1462', slug: 'lilla-edet', namn: "Lilla Edet", lan: "Västra Götalands län" },
  { kod: '1885', slug: 'lindesberg', namn: "Lindesberg", lan: "Örebro län" },
  { kod: '0580', slug: 'linkoping', namn: "Linköping", lan: "Östergötlands län" },
  { kod: '0781', slug: 'ljungby', namn: "Ljungby", lan: "Kronobergs län" },
  { kod: '2161', slug: 'ljusdal', namn: "Ljusdal", lan: "Gävleborgs län" },
  { kod: '1864', slug: 'ljusnarsberg', namn: "Ljusnarsberg", lan: "Örebro län" },
  { kod: '1262', slug: 'lomma', namn: "Lomma", lan: "Skåne län" },
  { kod: '2085', slug: 'ludvika', namn: "Ludvika", lan: "Dalarnas län" },
  { kod: '2580', slug: 'lulea', namn: "Luleå", lan: "Norrbottens län" },
  { kod: '1281', slug: 'lund', namn: "Lund", lan: "Skåne län" },
  { kod: '2481', slug: 'lycksele', namn: "Lycksele", lan: "Västerbottens län" },
  { kod: '1484', slug: 'lysekil', namn: "Lysekil", lan: "Västra Götalands län" },
  { kod: '2418', slug: 'mala', namn: "Malå", lan: "Västerbottens län" },
  { kod: '1280', slug: 'malmo', namn: "Malmö", lan: "Skåne län" },
  { kod: '2023', slug: 'malung-salen', namn: "Malung-Sälen", lan: "Dalarnas län" },
  { kod: '1493', slug: 'mariestad', namn: "Mariestad", lan: "Västra Götalands län" },
  { kod: '1463', slug: 'mark', namn: "Mark", lan: "Västra Götalands län" },
  { kod: '0767', slug: 'markaryd', namn: "Markaryd", lan: "Kronobergs län" },
  { kod: '1461', slug: 'mellerud', namn: "Mellerud", lan: "Västra Götalands län" },
  { kod: '0586', slug: 'mjolby', namn: "Mjölby", lan: "Östergötlands län" },
  { kod: '1481', slug: 'molndal', namn: "Mölndal", lan: "Västra Götalands län" },
  { kod: '0861', slug: 'monsteras', namn: "Mönsterås", lan: "Kalmar län" },
  { kod: '2062', slug: 'mora', namn: "Mora", lan: "Dalarnas län" },
  { kod: '0840', slug: 'morbylanga', namn: "Mörbylånga", lan: "Kalmar län" },
  { kod: '0583', slug: 'motala', namn: "Motala", lan: "Östergötlands län" },
  { kod: '0642', slug: 'mullsjo', namn: "Mullsjö", lan: "Jönköpings län" },
  { kod: '1430', slug: 'munkedal', namn: "Munkedal", lan: "Västra Götalands län" },
  { kod: '1762', slug: 'munkfors', namn: "Munkfors", lan: "Värmlands län" },
  { kod: '0182', slug: 'nacka', namn: "Nacka", lan: "Stockholms län" },
  { kod: '0682', slug: 'nassjo', namn: "Nässjö", lan: "Jönköpings län" },
  { kod: '1884', slug: 'nora', namn: "Nora", lan: "Örebro län" },
  { kod: '1962', slug: 'norberg', namn: "Norberg", lan: "Västmanlands län" },
  { kod: '2132', slug: 'nordanstig', namn: "Nordanstig", lan: "Gävleborgs län" },
  { kod: '2401', slug: 'nordmaling', namn: "Nordmaling", lan: "Västerbottens län" },
  { kod: '0581', slug: 'norrkoping', namn: "Norrköping", lan: "Östergötlands län" },
  { kod: '0188', slug: 'norrtalje', namn: "Norrtälje", lan: "Stockholms län" },
  { kod: '2417', slug: 'norsjo', namn: "Norsjö", lan: "Västerbottens län" },
  { kod: '0881', slug: 'nybro', namn: "Nybro", lan: "Kalmar län" },
  { kod: '0480', slug: 'nykoping', namn: "Nyköping", lan: "Södermanlands län" },
  { kod: '0140', slug: 'nykvarn', namn: "Nykvarn", lan: "Stockholms län" },
  { kod: '0192', slug: 'nynashamn', namn: "Nynäshamn", lan: "Stockholms län" },
  { kod: '2101', slug: 'ockelbo', namn: "Ockelbo", lan: "Gävleborgs län" },
  { kod: '1407', slug: 'ockero', namn: "Öckerö", lan: "Västra Götalands län" },
  { kod: '0509', slug: 'odeshog', namn: "Ödeshög", lan: "Östergötlands län" },
  { kod: '1060', slug: 'olofstrom', namn: "Olofström", lan: "Blekinge län" },
  { kod: '1880', slug: 'orebro', namn: "Örebro", lan: "Örebro län" },
  { kod: '1257', slug: 'orkelljunga', namn: "Örkelljunga", lan: "Skåne län" },
  { kod: '2284', slug: 'ornskoldsvik', namn: "Örnsköldsvik", lan: "Västernorrlands län" },
  { kod: '2034', slug: 'orsa', namn: "Orsa", lan: "Dalarnas län" },
  { kod: '1421', slug: 'orust', namn: "Orust", lan: "Västra Götalands län" },
  { kod: '1273', slug: 'osby', namn: "Osby", lan: "Skåne län" },
  { kod: '0882', slug: 'oskarshamn', namn: "Oskarshamn", lan: "Kalmar län" },
  { kod: '0117', slug: 'osteraker', namn: "Österåker", lan: "Stockholms län" },
  { kod: '2380', slug: 'ostersund', namn: "Östersund", lan: "Jämtlands län" },
  { kod: '0382', slug: 'osthammar', namn: "Östhammar", lan: "Uppsala län" },
  { kod: '1256', slug: 'ostra-goinge', namn: "Östra Göinge", lan: "Skåne län" },
  { kod: '2121', slug: 'ovanaker', namn: "Ovanåker", lan: "Gävleborgs län" },
  { kod: '2513', slug: 'overkalix', namn: "Överkalix", lan: "Norrbottens län" },
  { kod: '2518', slug: 'overtornea', namn: "Övertorneå", lan: "Norrbottens län" },
  { kod: '0481', slug: 'oxelosund', namn: "Oxelösund", lan: "Södermanlands län" },
  { kod: '2521', slug: 'pajala', namn: "Pajala", lan: "Norrbottens län" },
  { kod: '1402', slug: 'partille', namn: "Partille", lan: "Västra Götalands län" },
  { kod: '1275', slug: 'perstorp', namn: "Perstorp", lan: "Skåne län" },
  { kod: '2581', slug: 'pitea', namn: "Piteå", lan: "Norrbottens län" },
  { kod: '2303', slug: 'ragunda', namn: "Ragunda", lan: "Jämtlands län" },
  { kod: '2031', slug: 'rattvik', namn: "Rättvik", lan: "Dalarnas län" },
  { kod: '2409', slug: 'robertsfors', namn: "Robertsfors", lan: "Västerbottens län" },
  { kod: '1081', slug: 'ronneby', namn: "Ronneby", lan: "Blekinge län" },
  { kod: '1785', slug: 'saffle', namn: "Säffle", lan: "Värmlands län" },
  { kod: '1981', slug: 'sala', namn: "Sala", lan: "Västmanlands län" },
  { kod: '0128', slug: 'salem', namn: "Salem", lan: "Stockholms län" },
  { kod: '2181', slug: 'sandviken', namn: "Sandviken", lan: "Gävleborgs län" },
  { kod: '2082', slug: 'sater', namn: "Säter", lan: "Dalarnas län" },
  { kod: '0684', slug: 'savsjo', namn: "Sävsjö", lan: "Jönköpings län" },
  { kod: '0191', slug: 'sigtuna', namn: "Sigtuna", lan: "Stockholms län" },
  { kod: '1291', slug: 'simrishamn', namn: "Simrishamn", lan: "Skåne län" },
  { kod: '1265', slug: 'sjobo', namn: "Sjöbo", lan: "Skåne län" },
  { kod: '1495', slug: 'skara', namn: "Skara", lan: "Västra Götalands län" },
  { kod: '2482', slug: 'skelleftea', namn: "Skellefteå", lan: "Västerbottens län" },
  { kod: '1904', slug: 'skinnskatteberg', namn: "Skinnskatteberg", lan: "Västmanlands län" },
  { kod: '1496', slug: 'skovde', namn: "Skövde", lan: "Västra Götalands län" },
  { kod: '1264', slug: 'skurup', namn: "Skurup", lan: "Skåne län" },
  { kod: '2061', slug: 'smedjebacken', namn: "Smedjebacken", lan: "Dalarnas län" },
  { kod: '2182', slug: 'soderhamn', namn: "Söderhamn", lan: "Gävleborgs län" },
  { kod: '0582', slug: 'soderkoping', namn: "Söderköping", lan: "Östergötlands län" },
  { kod: '0181', slug: 'sodertalje', namn: "Södertälje", lan: "Stockholms län" },
  { kod: '2283', slug: 'solleftea', namn: "Sollefteå", lan: "Västernorrlands län" },
  { kod: '0163', slug: 'sollentuna', namn: "Sollentuna", lan: "Stockholms län" },
  { kod: '0184', slug: 'solna', namn: "Solna", lan: "Stockholms län" },
  { kod: '1083', slug: 'solvesborg', namn: "Sölvesborg", lan: "Blekinge län" },
  { kod: '2422', slug: 'sorsele', namn: "Sorsele", lan: "Västerbottens län" },
  { kod: '1427', slug: 'sotenas', namn: "Sotenäs", lan: "Västra Götalands län" },
  { kod: '1230', slug: 'staffanstorp', namn: "Staffanstorp", lan: "Skåne län" },
  { kod: '1415', slug: 'stenungsund', namn: "Stenungsund", lan: "Västra Götalands län" },
  { kod: '0180', slug: 'stockholm', namn: "Stockholm", lan: "Stockholms län" },
  { kod: '1760', slug: 'storfors', namn: "Storfors", lan: "Värmlands län" },
  { kod: '2421', slug: 'storuman', namn: "Storuman", lan: "Västerbottens län" },
  { kod: '0486', slug: 'strangnas', namn: "Strängnäs", lan: "Södermanlands län" },
  { kod: '1486', slug: 'stromstad', namn: "Strömstad", lan: "Västra Götalands län" },
  { kod: '2313', slug: 'stromsund', namn: "Strömsund", lan: "Jämtlands län" },
  { kod: '0183', slug: 'sundbyberg', namn: "Sundbyberg", lan: "Stockholms län" },
  { kod: '2281', slug: 'sundsvall', namn: "Sundsvall", lan: "Västernorrlands län" },
  { kod: '1766', slug: 'sunne', namn: "Sunne", lan: "Värmlands län" },
  { kod: '1907', slug: 'surahammar', namn: "Surahammar", lan: "Västmanlands län" },
  { kod: '1214', slug: 'svalov', namn: "Svalöv", lan: "Skåne län" },
  { kod: '1263', slug: 'svedala', namn: "Svedala", lan: "Skåne län" },
  { kod: '1465', slug: 'svenljunga', namn: "Svenljunga", lan: "Västra Götalands län" },
  { kod: '0160', slug: 'taby', namn: "Täby", lan: "Stockholms län" },
  { kod: '1435', slug: 'tanum', namn: "Tanum", lan: "Västra Götalands län" },
  { kod: '1472', slug: 'tibro', namn: "Tibro", lan: "Västra Götalands län" },
  { kod: '1498', slug: 'tidaholm', namn: "Tidaholm", lan: "Västra Götalands län" },
  { kod: '0360', slug: 'tierp', namn: "Tierp", lan: "Uppsala län" },
  { kod: '2262', slug: 'timra', namn: "Timrå", lan: "Västernorrlands län" },
  { kod: '0763', slug: 'tingsryd', namn: "Tingsryd", lan: "Kronobergs län" },
  { kod: '1419', slug: 'tjorn', namn: "Tjörn", lan: "Västra Götalands län" },
  { kod: '1270', slug: 'tomelilla', namn: "Tomelilla", lan: "Skåne län" },
  { kod: '1473', slug: 'toreboda', namn: "Töreboda", lan: "Västra Götalands län" },
  { kod: '0834', slug: 'torsas', namn: "Torsås", lan: "Kalmar län" },
  { kod: '1737', slug: 'torsby', namn: "Torsby", lan: "Värmlands län" },
  { kod: '0687', slug: 'tranas', namn: "Tranås", lan: "Jönköpings län" },
  { kod: '1452', slug: 'tranemo', namn: "Tranemo", lan: "Västra Götalands län" },
  { kod: '1287', slug: 'trelleborg', namn: "Trelleborg", lan: "Skåne län" },
  { kod: '1488', slug: 'trollhattan', namn: "Trollhättan", lan: "Västra Götalands län" },
  { kod: '0488', slug: 'trosa', namn: "Trosa", lan: "Södermanlands län" },
  { kod: '0138', slug: 'tyreso', namn: "Tyresö", lan: "Stockholms län" },
  { kod: '1485', slug: 'uddevalla', namn: "Uddevalla", lan: "Västra Götalands län" },
  { kod: '1491', slug: 'ulricehamn', namn: "Ulricehamn", lan: "Västra Götalands län" },
  { kod: '2480', slug: 'umea', namn: "Umeå", lan: "Västerbottens län" },
  { kod: '0139', slug: 'upplands-bro', namn: "Upplands-Bro", lan: "Stockholms län" },
  { kod: '0114', slug: 'upplands-vasby', namn: "Upplands Väsby", lan: "Stockholms län" },
  { kod: '0380', slug: 'uppsala', namn: "Uppsala", lan: "Uppsala län" },
  { kod: '0760', slug: 'uppvidinge', namn: "Uppvidinge", lan: "Kronobergs län" },
  { kod: '0584', slug: 'vadstena', namn: "Vadstena", lan: "Östergötlands län" },
  { kod: '0665', slug: 'vaggeryd', namn: "Vaggeryd", lan: "Jönköpings län" },
  { kod: '0563', slug: 'valdemarsvik', namn: "Valdemarsvik", lan: "Östergötlands län" },
  { kod: '0115', slug: 'vallentuna', namn: "Vallentuna", lan: "Stockholms län" },
  { kod: '1487', slug: 'vanersborg', namn: "Vänersborg", lan: "Västra Götalands län" },
  { kod: '2460', slug: 'vannas', namn: "Vännäs", lan: "Västerbottens län" },
  { kod: '2021', slug: 'vansbro', namn: "Vansbro", lan: "Dalarnas län" },
  { kod: '1470', slug: 'vara', namn: "Vara", lan: "Västra Götalands län" },
  { kod: '1383', slug: 'varberg', namn: "Varberg", lan: "Hallands län" },
  { kod: '1442', slug: 'vargarda', namn: "Vårgårda", lan: "Västra Götalands län" },
  { kod: '0120', slug: 'varmdo', namn: "Värmdö", lan: "Stockholms län" },
  { kod: '0683', slug: 'varnamo', namn: "Värnamo", lan: "Jönköpings län" },
  { kod: '1980', slug: 'vasteras', namn: "Västerås", lan: "Västmanlands län" },
  { kod: '0883', slug: 'vastervik', namn: "Västervik", lan: "Kalmar län" },
  { kod: '0187', slug: 'vaxholm', namn: "Vaxholm", lan: "Stockholms län" },
  { kod: '0780', slug: 'vaxjo', namn: "Växjö", lan: "Kronobergs län" },
  { kod: '1233', slug: 'vellinge', namn: "Vellinge", lan: "Skåne län" },
  { kod: '0685', slug: 'vetlanda', namn: "Vetlanda", lan: "Jönköpings län" },
  { kod: '2462', slug: 'vilhelmina', namn: "Vilhelmina", lan: "Västerbottens län" },
  { kod: '0884', slug: 'vimmerby', namn: "Vimmerby", lan: "Kalmar län" },
  { kod: '2404', slug: 'vindeln', namn: "Vindeln", lan: "Västerbottens län" },
  { kod: '0428', slug: 'vingaker', namn: "Vingåker", lan: "Södermanlands län" },
  { kod: '0512', slug: 'ydre', namn: "Ydre", lan: "Östergötlands län" },
  { kod: '1286', slug: 'ystad', namn: "Ystad", lan: "Skåne län" },
];

export const GILTIGA_KOMMUNSLUGS: ReadonlySet<string> = new Set(KOMMUNFACIT.map((k) => k.slug));

/** Länet en giltig kommunslug hör till, eller undefined om sluggen inte finns i facit. */
export function lanForKommunSlug(slug: string): string | undefined {
  return KOMMUNFACIT.find((k) => k.slug === slug)?.lan;
}
